# Build settings
markdown: kramdown
highlighter: pygments

# Site settings
title: "francisco javier arceo"
description: > # this means to ignore newlines until "email:"
   

url: http://franciscojavierarceo.github.io

email: fja2114@columbia.edu
#blog logo
logo: "/assets/images/df_logo.png"
# blog cover
cover: "/assets/images/background.jpg"

name: 'francisco javier arceo'
author: 'francisco javier arceo'
author_image: "/assets/images/author.jpg"

paginate:	5
paginate_path: "/blog/page:num"
permalink: /:categories/:year/:month/:day/:title 

# social icons and sharing options
social:
  - icon:	facebook
    url:	
    desc: 
    share_url: http://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/franciscojavierarceo
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	
    desc:	
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:  https://www.linkedin.com/in/franciscojavierarceo
    desc: Connect with me on linkedin
    share_url:
    share_title:
    share_link:    
